ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

# To build a fresh box, from the top dir of this repository:
#
# * vagrant destroy
# * VAGRANT_VAGRANTFILE=box-builder/Vagrantfile vagrant up
# * VAGRANT_VAGRANTFILE=box-builder/Vagrantfile vagrant halt
# * vagrant up --provision

Vagrant.configure("2") do |config|
    config.vm.box = "debian/stretch64"

    # Use METACPAN_DEVELOPER_* env vars to set vm hardware resources.
    vbox_custom = %w[cpus memory].map do |hw|
        key = "METACPAN_DEVELOPER_#{hw.upcase}"
        ENV[key] ? ["--#{hw}", ENV[key]] : []
    end.flatten

    config.vm.provider :virtualbox do |vb|
        vb.name = "mcstretch"
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        if not vbox_custom.empty?
            vb.customize [ "modifyvm", :id, *vbox_custom ]
        end
    end

    config.vm.provision :shell, :path => 'box-builder/provision.sh'
end
